#!/bin/sh
#
# xenum-inspect - run the preprocessor on a selected header or source file,
# and run it through xenum-postprocess to make it readable, so you can inspect
# the generated C++ code and data.
#
# Env-var CCC is the compiler name, defaults to g++.
#
# Copyright 2018 Simon Lodal <simonl@parknet.dk>
# 


if [ -z "$1" ]; then
	echo "Synopsis: $0 FILENAME"
	echo "Run from xenum root dir."
	exit 1
fi
marker="$2"

#file=xenum/test/inc/test/xenum/xenums/FruitsNoNsNoCls.hpp
#file=xenum/test/src/xenums/Numbers.cpp
#file=xenum/test/src/xenums/FruitsInNsInCls.cpp
#file=xenum/test/src/xenums/FruitsInNsNoCls.cpp
#file=xenum/test/src/xenums/FruitsNoNsInCls.cpp
#file=xenum/test/src/xenums/FruitsNoNsNoCls.cpp
#file=xenum/test/src/xenums/Icmp.cpp
#file=test.cpp
#file=../exception.c++/exception/lib/src/Exception.cpp

INC=""
# To preprocess the unit testing xenums.
INC="${INC} -I xenum/test/inc/"
# To use the local Xenum.hpp, not the system-installed one.
INC="${INC} -I xenum/lib/inc/"

if [ -z "$CCC" ]; then
	CCC=g++
fi
$CCC -E -x c++ -std=c++11 -P -DXENUM_DEBUG_PP=1 $INC $1 | util/xenum-postprocess "$marker"
